### ISSUE TITLE
Zero downtime deployments are broken in Magento 2.3.0

### ISSUE THREAD

**Issue by dverkade** [davidalger/capistrano-magento2#116] opened 2018-12-06 13:13 UTC
Due to an issue in Magento 2.3.0 zero downtime deployments are broken. The command `setup:db:status` always returns the the schema is not up to date, so it's forcing deployments to be done with maintenance mode enabled.

More information: 
magento/magento2#19597

Probably not something that can be solved within capistrano, but should be known to everyone using it that it's not working anymore with Magento 2.3.0.

**Comment by davidalger** [comment] 2018-12-07 00:21
@dverkade Thanks for the report. I recently noticed this as well as I spun up and deployed the first 2.3.0 test/stage site with this. You are correct, it's not really something we can do much about in context of this tool, as the only thing we can do is rely on the input from bin/magento (which is currently reporting a false status).

Hopefully somebody at Magento will pickup that issue and be able to reproduce it, otherwise I may try and escalate it somehow.

**Comment by geerlingguy** [comment] 2019-02-14 23:17
It's also not limited to capistrano; we were using the same technique to detect whether a code deployment in a Kubernetes cluster needed to run updates... and now it is running updates on every code deploy because it always thinks they're needed.

**Comment by yanncharlou** [comment] 2019-02-15 13:11
You can try my ugly fix. If you can't wait for official clean fix : https://github.com/magento/magento2/issues/19597#issuecomment-463611130

**Comment by davidalger** [comment] 2020-03-30 03:33
Zero-down deployments do finally work again as of Magento 2.3.4. The database must have the setting `explicit_defaults_for_timestamp=on` configured on MySQL for the db schema management to agree with the actual schema in place for TIMESTAMP fields. Personally tested this on both MySQL and MariaDB and I can confirm the `setup:db:status` check reports clean again (as long as the above setting is in place): https://github.com/magento/magento2/issues/19597#issuecomment-580361785

~There is also a PR open to get a note regarding this setting added into Magento DevDocs: https://github.com/magento/devdocs/pull/6916~

**Update:** DevDocs has been updated to reflect this setting as required: https://devdocs.magento.com/guides/v2.3/install-gde/prereq/mysql.html#instgde-prereq-mysql-config

Going to go ahead and close this out now. Never really an issue with this gem, and as long as latest 2.3.x is used with correct MySQL configuration zero-down deployments should again be possible.

**Closed as completed by davidalger** 2020-03-30 03:33 UTC
