### ISSUE TITLE
Strange static-content:deploy error on 2.1.3 with 5.9

### ISSUE THREAD

**Issue by avra911** [davidalger/capistrano-magento2#61] opened 2017-02-21 15:47 UTC
### Preconditions

1. Install composer 1.3.0 or higher.
2. Check out Magento 2.1.3.
3. Install capistrano-magento2 5.9.

### Steps to reproduce

1. configure and run `cap production deploy`.

### Expected result

1.  Deploy runs fine.

### Actual result

1. Part of the log ( I added `-vv` for debugging purpose to static content generation command, so the output has more details, not only errors count )
```
02 Processing file 'requirejs/requirejs' for area 'frontend', theme 'NAMESPACE/nec', locale 'en_US'
02 	Deploying the file to 'frontend/NAMESPACE/nec/en_US/requirejs/requireminjs'
02 Processing file 'requirejs/domReadyjs' for area 'frontend', theme 'NAMESPACE/nec', locale 'en_US'
02 	Deploying the file to 'frontend/NAMESPACE/nec/en_US/requirejs/domReadyminjs'
02 Processing file 'js-translationjson' for area 'frontend', theme 'NAMESPACE/nec', locale 'en_US'
02 	Deploying the file to 'frontend/NAMESPACE/nec/en_US/js-translationjson'
02 #0 /var/www/magento/releases/20170221151910/vendor/colinmollenhour/cache-backend-redis/Cm/Cache/Backend/Redisphp(313): Credis_Client->__call('hget', Array)
02 #1 /var/www/magento/releases/20170221151910/vendor/magento/zendframework1/library/Zend/Cache/Corephp(390): Cm_Cache_Backend_Redis->save('a:105:{i:123;s:', '537_TRANSLATE_E', Array, false)
02 #2 /var/www/magento/releases/20170221151910/vendor/magento/framework/Cache/Corephp(74): Zend_Cache_Core->save('a:105:{i:123;s:', '537_TRANSLATE_E', Array, false, 8)
02 #3 /var/www/magento/releases/20170221151910/vendor/magento/framework/Cache/Frontend/Adapter/Zendphp(47): Magento\Framework\Cache\Core->save('a:105:{i:123;s:', 'TRANSLATE_EN_US', Array, false)
02 #4 /var/www/magento/releases/20170221151910/vendor/magento/framework/Cache/Frontend/Decorator/Barephp(75): Magento\Framework\Cache\Frontend\Adapter\Zend->save('a:105:{i:123;s:', 'translate_en_US', Array, false)
02 #5 /var/www/magento/releases/20170221151910/vendor/magento/framework/Cache/Frontend/Decorator/TagScopephp(49): Magento\Framework\Cache\Frontend\Decorator\Bare->save('a:105:{i:123;s:', 'translate_en_US', Array, false)
02 #6 /var/www/magento/releases/20170221151910/vendor/magento/framework/Cache/Frontend/Decorator/Barephp(75): Magento\Framework\Cache\Frontend\Decorator\TagScope->save('a:105:{i:123;s:', 'translate_en_US', Array, false)
02 #7 /var/www/magento/releases/20170221151910/vendor/magento/framework/Cache/Frontend/Decorator/Barephp(75): Magento\Framework\Cache\Frontend\Decorator\Bare->save('a:105:{i:123;s:', 'translate_en_US', Array, false)
02 #8 /var/www/magento/releases/20170221151910/vendor/magento/framework/App/Cache/Type/AccessProxyphp(85): Magento\Framework\Cache\Frontend\Decorator\Bare->save('a:105:{i:123;s:', 'translate_en_US', Array, false)
02 #9 /var/www/magento/releases/20170221151910/vendor/magento/framework/Cache/Frontend/Decorator/Barephp(75): Magento\Framework\App\Cache\Type\AccessProxy->save('a:105:{i:123;s:', 'translate_en_US', Array, false)
02 #10 /var/www/magento/releases/20170221151910/vendor/magento/framework/Cache/Frontend/Decorator/TagScopephp(49): Magento\Framework\Cache\Frontend\Decorator\Bare->save('a:105:{i:123;s:', 'translate_en_US', Array, false)
02 #11 /var/www/magento/releases/20170221151910/vendor/magento/framework/Translatephp(489): Magento\Framework\Cache\Frontend\Decorator\TagScope->save('a:105:{i:123;s:', 'translate_en_US', Array, false)
02 #12 /var/www/magento/releases/20170221151910/vendor/magento/framework/Translatephp(185): Magento\Framework\Translate->_saveCache()
02 #13 /var/www/magento/releases/20170221151910/vendor/magento/framework/App/Areaphp(240): Magento\Framework\Translate->loadData(NULL, false)
02 #14 /var/www/magento/releases/20170221151910/vendor/magento/framework/App/Areaphp(211): Magento\Framework\App\Area->_initTranslate()
02 #15 /var/www/magento/releases/20170221151910/vendor/magento/framework/App/Areaphp(138): Magento\Framework\App\Area->_loadPart('translate')
02 #16 /var/www/magento/releases/20170221151910/vendor/magento/module-translation/Model/Json/PreProcessorphp(84): Magento\Framework\App\Area->load('translate')
02 #17 /var/www/magento/releases/20170221151910/vendor/magento/framework/View/Asset/PreProcessor/Poolphp(74): Magento\Translation\Model\Json\PreProcessor->process(Object(Magento\Framework\View\Asset\PreProcessor\Chain))
02 #18 /var/www/magento/releases/20170221151910/vendor/magento/framework/View/Asset/Sourcephp(152): Magento\Framework\View\Asset\PreProcessor\Pool->process(Object(Magento\Framework\View\Asset\PreProcessor\Chain))
02 #19 /var/www/magento/releases/20170221151910/vendor/magento/framework/View/Asset/Sourcephp(105): Magento\Framework\View\Asset\Source->preProcess(Object(Magento\Framework\View\Asset\File))
02 #20 /var/www/magento/releases/20170221151910/vendor/magento/framework/View/Asset/Filephp(150): Magento\Framework\View\Asset\Source->getFile(Object(Magento\Framework\View\Asset\File))
02 #21 /var/www/magento/releases/20170221151910/vendor/magento/framework/App/View/Asset/Publisherphp(73): Magento\Framework\View\Asset\File->getSourceFile()
02 #22 /var/www/magento/releases/20170221151910/vendor/magento/framework/App/View/Asset/Publisherphp(61): Magento\Framework\App\View\Asset\Publisher->publishAsset(Object(Magento\Framework\View\Asset\File))
02 #23 /var/www/magento/releases/20170221151910/vendor/magento/module-deploy/Model/Deploy/LocaleDeployphp(398): Magento\Framework\App\View\Asset\Publisher->publish(Object(Magento\Framework\View\Asset\File))
02 #24 /var/www/magento/releases/20170221151910/vendor/magento/module-deploy/Model/Deploy/LocaleDeployphp(235): Magento\Deploy\Model\Deploy\LocaleDeploy->deployFile('js-translation', 'frontend', 'Magento/blank', 'en_US', NULL)
02 #25 [internal function]: Magento\Deploy\Model\Deploy\LocaleDeploy->deploy('frontend', 'Magento/blank', 'en_US')
02 #26 /var/www/magento/releases/20170221151910/vendor/magento/framework/App/Statephp(171): call_user_func_array(Array, Array)
02 #27 /var/www/magento/releases/20170221151910/vendor/magento/module-deploy/Model/DeployManagerphp(175): Magento\Framework\App\State->emulateAreaCode('frontend', Array, Array)
02 #28 [internal function]: Magento\Deploy\Model\DeployManager->Magento\Deploy\Model\{closure}(Object(Magento\Deploy\Model\Process))
02 #29 /var/www/magento/releases/20170221151910/vendor/magento/module-deploy/Model/Processphp(53): call_user_func(Object(Closure), Object(Magento\Deploy\Model\Process))
02 #30 /var/www/magento/releases/20170221151910/vendor/magento/module-deploy/Model/ProcessManagerphp(55): Magento\Deploy\Model\Process->run()
02 #31 /var/www/magento/releases/20170221151910/vendor/magento/module-deploy/Model/ProcessQueueManagerphp(152): Magento\Deploy\Model\ProcessManager->fork(Object(Closure))
02 #32 /var/www/magento/releases/20170221151910/vendor/magento/module-deploy/Model/ProcessQueueManagerphp(130): Magento\Deploy\Model\ProcessQueueManager->fork(Object(Magento\Deploy\Model\ProcessTask))
02 #33 /var/www/magento/releases/20170221151910/vendor/magento/module-deploy/Model/ProcessQueueManagerphp(88): Magento\Deploy\Model\ProcessQueueManager->internalQueueProcess(Array, Array)
02 #34 /var/www/magento/releases/20170221151910/vendor/magento/module-deploy/Model/DeployManagerphp(187): Magento\Deploy\Model\ProcessQueueManager->process()
02 #35 /var/www/magento/releases/20170221151910/vendor/magento/module-deploy/Model/DeployManagerphp(122): Magento\Deploy\Model\DeployManager->runInParallel(Object(Magento\Deploy\Model\DeployStrategyProvider))
02 #36 /var/www/magento/releases/20170221151910/vendor/magento/module-deploy/Console/Command/DeployStaticContentCommandphp(386): Magento\Deploy\Model\DeployManager->deploy()
02 #37 /var/www/magento/releases/20170221151910/vendor/symfony/console/Symfony/Component/Console/Command/Commandphp(257): Magento\Deploy\Console\Command\DeployStaticContentCommand->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
02 #38 /var/www/magento/releases/20170221151910/vendor/symfony/console/Symfony/Component/Console/Applicationphp(874): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
02 #39 /var/www/magento/releases/20170221151910/vendor/symfony/console/Symfony/Component/Console/Applicationphp(195): Symfony\Component\Console\Application->doRunCommand(Object(Magento\Deploy\Console\Command\DeployStaticContentCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
02 #40 /var/www/magento/releases/20170221151910/vendor/magento/framework/Console/Cliphp(96): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
02 #41 /var/www/magento/releases/20170221151910/vendor/symfony/console/Symfony/Component/Console/Applicationphp(126): Magento\Framework\Console\Cli->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
02 #42 /var/www/magento/releases/20170221151910/bin/magento(23): Symfony\Component\Console\Application->run()
02 #43 {main}
02 
02 Successful: 2249 files; errors: 1
```

What could possibly be wrong, because while running `setup:static-content:deploy` from magento itself, it works, with no errors?! Please advice!

I also opened a question in magento repository: https://github.com/magento/magento2/issues/8643.

Thanks in advanced!

**Comment by erikhansen** [comment] 2017-02-21 19:42
@avra911 A couple of things you might try:

1. Try re-running the Capistrano deploy command to see if the issue is reproducible. The error is happening when cache data is being saved to Redis, so it could very well be a glitch that may not happen again if you try to re-deploy.
2. If you are still getting the same error, when the error occurs, SSH into the environment, cd to the failed release directory (e.g. `cd /var/www/magento/releases/20170221151910/`) and run the exact `setup:static-content:deploy` command that Capistrano tried to run to see if you can reproduce the error. You can find the exact command in the `log/capistrano.log` file.

**Comment by avra911** [comment] 2017-02-21 19:54
Hi, @erikhansen 

Thank you very much for the fast feedback on this.

1. Re-running capistrano deploy gives errors most of the times, see: http://nimb.ws/dTZ5JQ. The error is random, but >80% of the times it fails in a particular project only, it did not happened in any other sites/projects. However what I discover is that sometimes is a different file from static-content which fails, it not always `js-translation.json`. The command which failed was `bin/magento setup:static-content:deploy en_US`, reproducible even outside capistrano, by running  `ssh user@host.tld  /usr/bin/env php -f /path_to_site/bin/magento -- setup:static-content:deploy en_US | stdbuf -o0 tr -d .`.

2. If I logged in to the server where the site is located, manually running the command which failed, it is always a success, it never fails, so it means it is only effecting while using remote command. I tried multiple times and it was always working directly from magento. I even created all the steps which deploys is doing, in order to reproduce it, but no luck.

Is a bit weird and I wanted some other feedback, tomorrow I will try to debug exactly that error (by adding some extra dump to the output) and get more details.

Best regards!

PS: I thought it might not be related to magento, because I discovered it while using capistrano, but now I doubt about that. Now I think it might not be related at all to capistrano.

**Comment by erikhansen** [comment] 2017-02-21 20:04
@avra911 Since it doesn't happen consistently, then it's almost certainly not an issue with the capistrano-magento2 Gem, but rather something in your server configuration that is being triggered by the deployment process. I just saw the edit you made to the commend above and I agree with your assessment. I would recommend closing this issue.

**Comment by avra911** [comment] 2017-02-21 20:04
Sure, @erikhansen, thanks a lot!

**Comment by avra911** [comment] 2017-03-08 14:33
Hi, @erikhansen

I am reopening the issue because it seems a workaround might be to set the number of jobs for the static content deploy to 1, by using `--jobs` (-j) which, from magento docs it means: `Enable parallel processing using the specified number of jobs. The default is 4. To cause the task to run in one process (for example, if your system does not support process forking), use --jobs 1.`

Would be nice to have the option to set that in deploy.rb parameters, with a default: 1 (for example named `magento_deploy_jobs`).

**Closed as completed** 2017-04-10 17:46 UTC

**Comment by davidalger** [comment] 2017-04-10 17:50
@avra911 I've added a setting so this argument can be configured. Details can be found in the readme and/or the above commit.

I opted to default to `nil` which leaves the default at whatever the default is for `bin/magento` as the `--jobs` setting is only actually available in Magento 2.1.1 and later. This allows me to issue a warning if someone tries to use the setting on an unsupported version of Magento, and also keeps the default in line with whatever the Magento platform sets it to in the future (although I don't see it changing). 

The underlying bug you're running into is definitely a Magento core issue (so keep that Magento issue open!), but to workaround it in the meantime, you can now add the following to your `config.rb`:

```ruby
set :magento_deploy_jobs, 1
```

**Comment by PascalBrouwers** [comment] 2017-05-03 13:03
Actually it's an issue running Magento with Redis cache. See also: https://github.com/magento/magento2/issues/8643 where the same solution is provided (-j 1)

**Comment by ed007m** [comment] 2017-09-07 11:03
During cap production deploy i've got this issue again.
Console output example
`00:00 magento:setup:static-content:deploy
      01 touch /home/webuser/websites/radco.ecomitize.com/public_html/current/pub/static/deployed_version.txt
    ✔ 01 webuser@main9.websupport911.com 0.497s
      02 set -o pipefail; /usr/bin/env php -f bin/magento -- setup:static-content:deploy en_US | stdbuf -o0 tr -d .
      02 Requested languages: en_US
      02 Requested areas: frontend, adminhtml
      02 Requested themes: Magento/blank, Magento/luma, Ecomitize/eco, Magento/backend
      02 === frontend -> Magento/blank -> en_US ===
      02 === frontend -> Magento/luma -> en_US ===
      02 === frontend -> Ecomitize/eco -> en_US ===
      02 === adminhtml -> Magento/backend -> en_US ===
      02
      02 Successful: 2551 files; errors: 1
      02 ---
      02
      02
      02 Successful: 2626 files; errors: 1
      02 ---
      02
      02
      02 Successful: 2707 files; errors: 1
      02 ---
      02
      02
      02 Successful: 2697 files; errors: 0
      02 ---
      02
      02 === Minify templates ===
      02
      02 Successful: 1427 files modified
      02 ---
      02
      02 New version of deployed files: 1504780628
cap aborted!
Exception while executing as webuser@main9.websupport911.com: magento exit status: 1
magento stdout: Requested languages: en_US
Requested areas: frontend, adminhtml
Requested themes: Magento/blank, Magento/luma, Ecomitize/eco, Magento/backend
=== frontend -> Magento/blank -> en_US ===
=== frontend -> Magento/luma -> en_US ===
=== frontend -> Ecomitize/eco -> en_US ===
=== adminhtml -> Magento/backend -> en_US ===

Successful: 2551 files; errors: 1
---


Successful: 2626 files; errors: 1
---


Successful: 2707 files; errors: 1
---


Successful: 2697 files; errors: 0
---

=== Minify templates ===

Successful: 1427 files modified
---

New version of deployed files: 1504780628
magento stderr: Nothing written
/var/lib/gems/2.1.0/gems/sshkit-1.14.0/lib/sshkit/runners/parallel.rb:15:in `rescue in block (2 levels) in execute'
/var/lib/gems/2.1.0/gems/sshkit-1.14.0/lib/sshkit/runners/parallel.rb:11:in `block (2 levels) in execute'
Tasks: TOP => magento:setup:static-content:deploy`
