### ISSUE TITLE
Run setup:upgrade before compile assets

### ISSUE THREAD

**Issue by sebfie** [davidalger/capistrano-magento2#95] opened 2018-02-07 11:25 UTC
Hello,

It will be great to run setup:upgrade before compile assets. This way, we will not get errors like : 
- `Unable to resolve the source file for 'adminhtml/Theme/admin/fr_FR/js/theme.js'`

Reproduction steps : 
- Create an admin theme
- Apply this admin theme by default with a file web/theme.js
- Deploy

Command `bin/magento setup:static-content:deploy` will have errors

**Comment by giacmir** [comment] 2018-02-07 11:34
But in this way you will have to put the website in maintenance for much longer.

**Comment by sebfie** [comment] 2018-02-07 11:35
Yes, but it will work :)

**Comment by giacmir** [comment] 2018-02-07 11:37
Uhm, creating admin themes is not something you do every day, while deploy changes it is, and often even several times per day. So I think that the tradeoff is not worthy.

**Comment by sebfie** [comment] 2018-02-07 11:38
Ok, but this issue will maybe help someone one day :)

**Comment by sebfie** [comment] 2018-02-07 11:39
Anyway, thx for this project !

**Comment by giacmir** [comment] 2018-02-07 11:41
@sebfie Wait wait... I'm not the owner, I just gave my opinion.... :-)

please reopen the issue and let's wait for some other to join discussion.

**Comment by danslo** [comment] 2018-02-07 11:51
The error message is different, but this issue is actually a duplicate of #63 (and several others that were a duplicate of that as well).

See https://github.com/davidalger/capistrano-magento2/issues/63#issuecomment-293102757.

**Comment by davidalger** [comment] 2018-02-07 17:32
This is indeed a duplicate of #63 and I don't have a solution other than suggesting that if it is more important to you that your deployer run setup:upgrade before static content compilation, you are welcome to override / re-define portions of the deploy routine. That will involve a decent knowledge of ruby, but is possible. If you're going to do that, I'd suggest checking out the docs on http://capistranorb.com/ etc.

All that said, I would highly recommend against doing this. Putting setup upgrade before static asset compilation means minutes of downtime (maintenance mode) vs 2-7 seconds (or less) as static asset generation and DI compilation is the largest portion of the deploy routine time-wise. What we do over here when pushing a completely new theme out is to manually add it to the database _before_ running the deploy so that the deploy will succeed (https://github.com/magento/magento2/issues/2797#issuecomment-216776283). Alternatively, I believe (although have not personally tried it out yet) the config.php file in 2.2 can be used to set the theme data. This allows 2.2 to deploy without a database connection and thus should allow deploy of a new theme without running into this. But like I said, I haven't had the chance to run this scenario in 2.2 as of yet.

Closing as duplicate of #63.

**Closed as completed by davidalger** 2018-02-07 17:32 UTC
Labels: wontfix
