### ISSUE TITLE
Newly added theme messes with next deployment.

### ISSUE THREAD

**Issue by wintermute-84** [davidalger/capistrano-magento2#78] opened 2017-08-19 08:04 UTC
Sorry for spamming another issue, if it's something you will address in v0.7.0 anyway, you might just close it.

The problem occurs when adding new theme module using composer.json. 
The static-content deploy fails finding new theme during capistrano deployment process.

The reason being setup:upgrade scripts are executed after static-content:deploy meaning that magento is not yet fully aware about the new module during static files generation.

As always, we appreciate any input.
Thanks.

**Comment by davidalger** [comment] 2017-08-19 22:18
@Dukeofvampires This is actually a duplicate of #63, so I will be closing it. Haven't had a chance to see if 2.2 exhibits same behavior, but the short version is this is due to how Magento 2.1 behaves and not something I can readily resolve. Recommend you go check that out for information as well as workarounds.

P.S. Just pushed up v0.7.0

**Closed as completed by davidalger** 2017-08-19 22:18 UTC
