### ISSUE TITLE
Bug in release 0.5.7

### ISSUE THREAD

**Issue by kieronlexel** [davidalger/capistrano-magento2#51] opened 2016-11-28 16:36 UTC
Magento 2 deployment is broken in this release with the addition of 'pipefail'.

Static content deployment now fails as it is not using 'php' i.e.

01:13 magento:setup:static-content:deploy
      01 touch /home/mage2lexeldevser/public_html/releases/20161128161238/pub/static/deployed_version.txt
      01 stdin: is not a tty
    ✔ 01 mage2lexeldevser@mage2.lexeldevserver.co.uk 0.088s
      02 set -o pipefail; magento setup:static-content:deploy en_GB | stdbuf -o0 tr -d .
      02 stdin: is not a tty
      02 bash: magento: command not found
(Backtrace restricted to imported tasks)
cap aborted!

This use to run as follows:

00:51 magento:setup:static-content:deploy
      01 touch /home/mage2lexeldevser/public_html/releases/20161124160928/pub/static/deployed_version.txt
      01 stdin: is not a tty
    ✔ 01 mage2lexeldevser@mage2.lexeldevserver.co.uk 0.076s
      02 php -f bin/magento -- setup:static-content:deploy en_GB -t Magento/luma -t Magento/backend | stdbuf -o0 tr -d .
      02 stdin: is not a tty
      02 Requested languages: en_GB

I've removed my capistrano-magento2-0.5.7 directory and rolled back to capistrano-magento2-0.5.6 to get this back to a working version.

Thanks.

**Comment by erikhansen** [comment] 2016-11-28 21:10
This is a duplicate of #50

**Comment by davidalger** [comment] 2016-11-28 23:30
@kieronlexel Thanks for reporting. I've just fixed this in 0.5.8. The bug was due to some odd behavior in how SSHKit treats commands once prefixes are applied and slipped into this update without being noticed due to a shortcut which exists in our test/stage deployment environments.

**Closed as completed** 2016-11-28 23:30 UTC

**Comment by kieronlexel** [comment] 2016-11-29 14:43
@davidalger - thanks for the update. On a side issue, I have deployed static content with en_GB globally i.e. for front and backend, however when I install an extension and deploy, the backend always reverts back to en_US and breaks. Do you know why this happens?
Can I specify in my deploy.rb two locales - one for frontend theme and one for backend theme to get round this? I'm unsure of the syntax if that is possible.

Many thanks.

**Comment by davidalger** [comment] 2016-11-29 20:52
@kieronlexel I'm not sure why M2 would be reverting to en_US after deploying an extension. As for deploying multiple locales, it can be done, but each local would be deployed for both frontend and backend themes. This wouldn't pose any problem per-se, just a little slower on the build part of the deploy.

See the Example Usage section in the deploy settings list in the README on how to do this: https://github.com/davidalger/capistrano-magento2/#magento-deploy-settings
